version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "21:55"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
      time: "21:55"
      timezone: "Europe/Rome"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "21:55"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 15
