[tool.poetry]
name = "nimg"
version = "0.3.5"
description = ""
authors = ["daniele arosio <daniele.arosio@cnr.it>"]
license = "BSD-3-Clause"
readme = "README.rst"
homepage = "https://bitbucket.org/darosio/nimg/"
repository = "https://bitbucket.org/darosio/nimg/"
keywords = ["ClopHensor", "ratio imaging", "image analysis", "chloride", "pH"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Unix Shell",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Development Status :: 2 - Pre-Alpha",
]
include = [
    "LICENSE.txt",
]


[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = ">=1.16"
pandas = ">=0.19"
scikit-image = ">=0.14"
# scikit-image = [
# {version = "0.13.1", python = "3.6.4"},
# {version = "~0.14.0", python = "^3.7"}
# ]
matplotlib = ">=2.0.0"
tifffile = ">2019.7.2"          #changed an OME recognition check and "IYX" -> "TCYX"
scipy = ">=0.18.1"
docopt = "^0.6.2"

[tool.poetry.scripts]
nimg = "nimg.scripts:main"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
coverage = {extras = ["toml"], version = "^6.3.2"}
pytest-cov = "^3.0.0"
ipykernel = "^6.13.0"
xdoctest = "^1.0.0"
Sphinx = "^4.0"
flake8 = "^4.0.1"
flake8-black = "^0.3.2"
flake8-bugbear = "^22.3.23"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
darglint = "^1.8.1"
safety = "^1.10.3"
Pygments = "^2.11.2"
ipython = "^8.2.0"
myst-parser = "^0.17.2"
flake8-bandit = "^3.0.0"
mypy = "^0.961"
types-setuptools = "^57.4.17"
data-science-types = "^0.2.23"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["nimg"]
omit = ["*__init__.py"]

[tool.coverage.report]
show_missing = true

# [tool.coverage.report]
# fail_under = 100

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
plugins = "numpy.typing.mypy_plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
