name: Build, Publish and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      # - name: Extract tag version
      #   id: version
      #   run: echo "value=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      #   # TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
      #   # echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      # - name: Generate release notes
      #   run: git cliff --tag "${{ steps.version.outputs.value }}" --latest -o RELEASE.md
      # - name: Confirm version
      #   run: echo "Generating release for version ${{ steps.version.outputs.value }}"
      # # - name: Generate release notes
      # #   # run: git cliff --tag "$VERSION" --latest -o RELEASE.md
      # #   run: git cliff --tag "$(git describe --tags --abbrev=0)" --latest -o RELEASE.md
      # # - name: Version check
      # #   run: echo "Generating release for version $(git describe --tags --abbrev=0)"
      - name: Generate Release Notes
        run: |
          git cliff --tag "${GITHUB_REF#refs/tags/}" -o RELEASE.md
          echo "Generated release notes for ${GITHUB_REF#refs/tags/}"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          bodyFile: RELEASE.md

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.6"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install base and hatch
        run: uv sync --locked --extra hatch
      - name: Build and publish
        run: |
          uv run hatch build
          uv run hatch publish --user=__token__ --auth=${{ secrets.PYPI_TOKEN }}
